# Generated by Django 4.2.13 on 2026-06-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="authentification.role"
            ),
        ),
    ]
