# Generated by Django 4.2.13 on 2026-06-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0007_compta_init_plan_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="onetimetoken",
            name="code",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="Code à 6 chiffres généré côté serveur — saisie manuelle",
                max_length=6,
            ),
        ),
    ]
