# Generated by Django 4.2.13 on 2026-06-13 10:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True, help_text="UUID du tenant extrait du JWT"
                    ),
                ),
                (
                    "nom",
                    models.CharField(help_text="Nom du département", max_length=100),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code unique du département dans le tenant",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description du rôle du département",
                        null=True,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Budget annuel alloué au département",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        default="XAF",
                        help_text="Devise du budget (XAF par défaut)",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="False = département archivé"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Département parent — null si racine",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sous_departements",
                        to="rh.departement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Département",
                "verbose_name_plural": "Départements",
                "db_table": "departements",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Poste",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True, help_text="UUID du tenant extrait du JWT"
                    ),
                ),
                (
                    "titre",
                    models.CharField(help_text="Intitulé du poste", max_length=100),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code unique du poste dans le tenant", max_length=50
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description des responsabilités du poste",
                        null=True,
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("junior", "Junior"),
                            ("mid", "Mid-level"),
                            ("senior", "Senior"),
                            ("manager", "Manager"),
                            ("directeur", "Directeur"),
                        ],
                        default="junior",
                        help_text="Niveau hiérarchique du poste",
                        max_length=20,
                    ),
                ),
                (
                    "salaire_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Salaire minimum pour ce poste",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "salaire_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Salaire maximum pour ce poste",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        default="XAF",
                        help_text="Devise de la grille salariale",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="False = poste archivé"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "departement",
                    models.ForeignKey(
                        help_text="Département auquel appartient ce poste",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postes",
                        to="rh.departement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poste",
                "verbose_name_plural": "Postes",
                "db_table": "postes",
                "ordering": ["titre"],
                "unique_together": {("tenant_id", "code")},
            },
        ),
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True, help_text="UUID du tenant extrait du JWT"
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID du User dans le service Auth",
                        null=True,
                    ),
                ),
                (
                    "employee_number",
                    models.CharField(
                        help_text="Matricule unique dans le tenant — auto-généré",
                        max_length=50,
                    ),
                ),
                ("first_name", models.CharField(help_text="Prénom", max_length=100)),
                (
                    "last_name",
                    models.CharField(help_text="Nom de famille", max_length=100),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="Date de naissance", null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Masculin"),
                            ("F", "Féminin"),
                            ("Other", "Autre"),
                        ],
                        default="M",
                        help_text="Genre — M/F/Other",
                        max_length=10,
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        default="Camerounaise",
                        help_text="Nationalité",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        help_text="Numéro CNI — sera chiffré en base",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "situation_familiale",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("celibataire", "Célibataire"),
                            ("marie", "Marié(e)"),
                            ("divorce", "Divorcé(e)"),
                            ("veuf", "Veuf/Veuve"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "nombre_enfants",
                    models.IntegerField(
                        default=0, help_text="Pour calcul allocations familiales"
                    ),
                ),
                (
                    "numero_cnps",
                    models.CharField(
                        blank=True,
                        help_text="Numéro CNPS — Caisse Nationale Prévoyance Sociale",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Adresse complète", null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Téléphone professionnel", max_length=20
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email professionnel unique dans le tenant",
                        max_length=254,
                    ),
                ),
                (
                    "email_perso",
                    models.EmailField(
                        blank=True,
                        help_text="Email personnel",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone_perso",
                    models.CharField(
                        blank=True,
                        help_text="Téléphone personnel",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "ville",
                    models.CharField(
                        blank=True, default="Douala", max_length=100, null=True
                    ),
                ),
                ("pays", models.CharField(default="Cameroun", max_length=100)),
                ("hire_date", models.DateField(help_text="Date d'embauche")),
                (
                    "date_fin_periode_essai",
                    models.DateField(
                        blank=True, help_text="Fin de la période d'essai", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("inactive", "Inactif"),
                            ("on_leave", "En congé"),
                            ("terminated", "Licencié/Démissionné"),
                            ("suspended", "Suspendu"),
                        ],
                        default="active",
                        help_text="Statut de l'employé",
                        max_length=20,
                    ),
                ),
                (
                    "type_employe",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("contractuel", "Contractuel"),
                            ("stagiaire", "Stagiaire"),
                            ("consultant", "Consultant"),
                        ],
                        default="permanent",
                        max_length=20,
                    ),
                ),
                (
                    "salaire_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Salaire de base mensuel brut",
                        max_digits=15,
                    ),
                ),
                ("devise", models.CharField(default="XAF", max_length=10)),
                (
                    "mode_paiement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("virement", "Virement bancaire"),
                            ("especes", "Espèces"),
                            ("mobile_money", "Mobile Money"),
                            ("cheque", "Chèque"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "numero_compte",
                    models.CharField(
                        blank=True,
                        help_text="Coordonnées bancaires",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("banque", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "photo_url",
                    models.URLField(
                        blank=True, help_text="URL de la photo de profil", null=True
                    ),
                ),
                (
                    "cv_url",
                    models.URLField(blank=True, help_text="URL du CV", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Département d'affectation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employes",
                        to="rh.departement",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager / supérieur hiérarchique direct",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordonnes",
                        to="rh.employe",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        help_text="Poste occupé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employes",
                        to="rh.poste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employé",
                "verbose_name_plural": "Employés",
                "db_table": "employes",
                "ordering": ["last_name", "first_name"],
                "unique_together": {
                    ("tenant_id", "employee_number"),
                    ("tenant_id", "email"),
                },
            },
        ),
        migrations.AddField(
            model_name="departement",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                help_text="Employé responsable du département",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departements_diriges",
                to="rh.employe",
            ),
        ),
        migrations.CreateModel(
            name="Contrat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True, help_text="UUID du tenant extrait du JWT"
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        help_text="Numéro unique auto-généré — ex: CTR-2024-001",
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CDI", "Contrat à Durée Indéterminée"),
                            ("CDD", "Contrat à Durée Déterminée"),
                            ("Interim", "Intérim"),
                            ("Stage", "Stage"),
                            ("Freelance", "Freelance"),
                        ],
                        help_text="Type de contrat conforme CDC",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(help_text="Date de début du contrat")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date de fin — null pour les CDI",
                        null=True,
                    ),
                ),
                (
                    "trial_period",
                    models.IntegerField(
                        blank=True,
                        help_text="Durée de la période d'essai en jours",
                        null=True,
                    ),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Salaire brut mensuel contractuel",
                        max_digits=15,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XAF",
                        help_text="Devise (XAF, EUR, USD...)",
                        max_length=10,
                    ),
                ),
                (
                    "work_hours_per_week",
                    models.DecimalField(
                        decimal_places=2,
                        default=40,
                        help_text="Heures de travail par semaine",
                        max_digits=5,
                    ),
                ),
                (
                    "periodicite_paie",
                    models.CharField(
                        choices=[
                            ("mensuel", "Mensuel"),
                            ("bimensuel", "Bimensuel"),
                            ("hebdomadaire", "Hebdomadaire"),
                        ],
                        default="mensuel",
                        help_text="Fréquence de paiement du salaire",
                        max_length=20,
                    ),
                ),
                (
                    "jours_conge_annuel",
                    models.IntegerField(
                        default=30, help_text="Nombre de jours de congé annuel"
                    ),
                ),
                (
                    "lieu_travail",
                    models.CharField(
                        blank=True,
                        help_text="Lieu de travail principal",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "poste",
                    models.CharField(
                        blank=True,
                        help_text="Intitulé du poste dans le contrat",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("actif", "Actif"),
                            ("expire", "Expiré"),
                            ("resilie", "Résilié"),
                            ("suspendu", "Suspendu"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Contrat actif ou archivé"
                    ),
                ),
                (
                    "motif_resiliation",
                    models.TextField(
                        blank=True,
                        help_text="Motif de résiliation du contrat",
                        null=True,
                    ),
                ),
                (
                    "date_resiliation",
                    models.DateField(
                        blank=True, help_text="Date de résiliation", null=True
                    ),
                ),
                (
                    "document_url",
                    models.URLField(
                        blank=True, help_text="URL du contrat signé numérisé", null=True
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date et heure de signature du contrat",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employé concerné par ce contrat",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrats",
                        to="rh.employe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrat",
                "verbose_name_plural": "Contrats",
                "db_table": "contrats",
                "ordering": ["-start_date"],
                "unique_together": {("tenant_id", "numero")},
            },
        ),
        migrations.CreateModel(
            name="Conge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True, help_text="UUID du tenant extrait du JWT"
                    ),
                ),
                (
                    "type_conge",
                    models.CharField(
                        choices=[
                            ("annuel", "Congé annuel"),
                            ("maladie", "Congé maladie"),
                            ("maternite", "Congé maternité"),
                            ("paternite", "Congé paternité"),
                            ("sans_solde", "Congé sans solde"),
                            ("exceptionnel", "Congé exceptionnel"),
                            ("recuperation", "Récupération"),
                            ("formation", "Formation"),
                            ("deces", "Décès famille"),
                        ],
                        help_text="Type de congé demandé",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(help_text="Date de début du congé")),
                ("end_date", models.DateField(help_text="Date de fin du congé")),
                (
                    "days",
                    models.IntegerField(
                        default=0,
                        help_text="Nombre de jours calendaires — calculé auto",
                    ),
                ),
                (
                    "jours_ouvres",
                    models.IntegerField(
                        default=0, help_text="Nombre de jours ouvrés — calculé auto"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Motif de la demande de congé", null=True
                    ),
                ),
                (
                    "piece_justificative",
                    models.URLField(
                        blank=True,
                        help_text="URL du justificatif (arrêt maladie, etc.)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                            ("annule", "Annulé"),
                        ],
                        default="pending",
                        help_text="Statut de la demande",
                        max_length=20,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, help_text="Date et heure de la décision", null=True
                    ),
                ),
                (
                    "commentaire_decision",
                    models.TextField(
                        blank=True,
                        help_text="Commentaire d'approbation ou motif de rejet",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="RH_MANAGER ayant approuvé ou rejeté",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conges_approuves",
                        to="rh.employe",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employé qui demande le congé",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conges",
                        to="rh.employe",
                    ),
                ),
                (
                    "remplacant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employé assurant l'intérim pendant le congé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remplacements",
                        to="rh.employe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Congé",
                "verbose_name_plural": "Congés",
                "db_table": "conges",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SoldeConges",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True, help_text="UUID du tenant extrait du JWT"
                    ),
                ),
                (
                    "type_conge",
                    models.CharField(
                        choices=[
                            ("annuel", "Congé annuel"),
                            ("maladie", "Congé maladie"),
                            ("sans_solde", "Congé sans solde"),
                            ("exceptionnel", "Congé exceptionnel"),
                        ],
                        help_text="Type de congé",
                        max_length=20,
                    ),
                ),
                ("annee", models.IntegerField(help_text="Année de référence du solde")),
                (
                    "jours_acquis",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total des jours acquis dans l'année",
                        max_digits=6,
                    ),
                ),
                (
                    "jours_pris",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total des jours pris dans l'année",
                        max_digits=6,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employé concerné",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soldes_conges",
                        to="rh.employe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solde de congés",
                "verbose_name_plural": "Soldes de congés",
                "db_table": "soldes_conges",
                "ordering": ["-annee", "type_conge"],
                "unique_together": {("employee", "type_conge", "annee")},
            },
        ),
        migrations.CreateModel(
            name="Presence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True, help_text="UUID du tenant extrait du JWT"
                    ),
                ),
                ("date", models.DateField(help_text="Date du pointage")),
                (
                    "heure_arrivee",
                    models.TimeField(
                        blank=True, help_text="Heure d'arrivée", null=True
                    ),
                ),
                (
                    "heure_depart",
                    models.TimeField(
                        blank=True, help_text="Heure de départ", null=True
                    ),
                ),
                (
                    "heures_travaillees",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculé depuis heure_arrivee et heure_depart",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "heures_supplementaires",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Heures supplémentaires effectuées",
                        max_digits=5,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("present", "Présent"),
                            ("absent", "Absent"),
                            ("retard", "Retard"),
                            ("conge", "En congé"),
                            ("ferie", "Jour férié"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True, help_text="Commentaire optionnel", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employé pointé",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presences",
                        to="rh.employe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Présence",
                "verbose_name_plural": "Présences",
                "db_table": "presences",
                "ordering": ["-date"],
                "unique_together": {("tenant_id", "employee", "date")},
            },
        ),
        migrations.CreateModel(
            name="FichePaie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True, help_text="UUID du tenant extrait du JWT"
                    ),
                ),
                ("mois", models.IntegerField(help_text="Mois de la fiche (1-12)")),
                ("annee", models.IntegerField(help_text="Année de la fiche")),
                (
                    "period",
                    models.CharField(
                        help_text="Période auto-générée ex: 2024-06", max_length=7
                    ),
                ),
                (
                    "salaire_base",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Salaire de base mensuel",
                        max_digits=15,
                    ),
                ),
                (
                    "heures_travaillees",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Heures travaillées dans le mois",
                        max_digits=7,
                    ),
                ),
                (
                    "heures_supplementaires",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Heures supplémentaires effectuées",
                        max_digits=7,
                    ),
                ),
                (
                    "taux_horaire_supp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Taux majoré des heures supplémentaires",
                        max_digits=10,
                    ),
                ),
                (
                    "bonuses",
                    models.JSONField(
                        default=dict,
                        help_text="\n                          Détail des primes en JSON.\n                          Ex: {\n                            'prime_transport': 30000,\n                            'prime_logement': 50000,\n                            'prime_rendement': 25000,\n                            'autres': 0\n                          }\n                          ",
                    ),
                ),
                (
                    "deductions",
                    models.JSONField(
                        default=dict,
                        help_text="\n                          Détail des déductions en JSON.\n                          Ex: {\n                            'cotisation_cnps': 44000,\n                            'impot_irpp': 35000,\n                            'credit_logement': 0,\n                            'autres': 0\n                          }\n                          ",
                    ),
                ),
                (
                    "gross",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Salaire brut = base + primes + heures supp",
                        max_digits=15,
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Salaire net = gross - total_deductions",
                        max_digits=15,
                    ),
                ),
                ("currency", models.CharField(default="XAF", max_length=10)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("valide", "Validé"),
                            ("paye", "Payé"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de validation par RH/Comptable",
                        null=True,
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de paiement effectif", null=True
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("virement", "Virement bancaire"),
                            ("especes", "Espèces"),
                            ("mobile_money", "Mobile Money"),
                            ("cheque", "Chèque"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "pdf_url",
                    models.URLField(
                        blank=True,
                        help_text="URL du bulletin de paie PDF généré",
                        null=True,
                    ),
                ),
                (
                    "journal_entry_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID de l'écriture SYSCOHADA dans le service Comptabilité",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contrat",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contrat de base pour le calcul",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fiches_paie",
                        to="rh.contrat",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employé concerné",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiches_paie",
                        to="rh.employe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche de paie",
                "verbose_name_plural": "Fiches de paie",
                "db_table": "fiches_paie",
                "ordering": ["-annee", "-mois"],
                "unique_together": {("tenant_id", "employee", "mois", "annee")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="departement",
            unique_together={("tenant_id", "code")},
        ),
    ]
