# Generated by Django 4.2.13 on 2026-06-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="presence",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="False = présence archivée"
            ),
        ),
        migrations.AlterField(
            model_name="presence",
            name="heures_supplementaires",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Heures supplémentaires",
                max_digits=5,
            ),
        ),
    ]
