# Generated by Django 4.2.13 on 2026-06-17 04:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0002_add_is_active_to_presence"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True, help_text="UUID du tenant extrait du JWT"
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("attestation_travail", "Attestation de travail"),
                            ("attestation_salaire", "Attestation de salaire"),
                            ("bulletin_paie_copie", "Copie de bulletin de paie"),
                        ],
                        help_text="Type de document demandé",
                        max_length=30,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente de traitement"),
                            ("approuvee", "Approuvée"),
                            ("rejetee", "Rejetée"),
                            ("annulee", "Annulée par l'employé"),
                        ],
                        default="en_attente",
                        help_text="Statut de traitement de la demande",
                        max_length=20,
                    ),
                ),
                (
                    "motif_demande",
                    models.TextField(
                        blank=True,
                        help_text="Raison de la demande (optionnel — ex: visa, prêt bancaire)",
                        null=True,
                    ),
                ),
                (
                    "traitee_par",
                    models.UUIDField(
                        blank=True,
                        help_text="auth_user_id du RH Manager ayant traité la demande",
                        null=True,
                    ),
                ),
                (
                    "traitee_le",
                    models.DateTimeField(
                        blank=True, help_text="Date et heure du traitement", null=True
                    ),
                ),
                (
                    "motif_rejet",
                    models.TextField(
                        blank=True,
                        help_text="Motif du rejet — obligatoire si statut=REJETEE",
                        null=True,
                    ),
                ),
                (
                    "document_data",
                    models.JSONField(
                        blank=True,
                        help_text="Données structurées du document généré — disponibles après approbation",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employé ayant soumis la demande",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_document",
                        to="rh.employe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de document",
                "verbose_name_plural": "Demandes de documents",
                "db_table": "demandes_document",
                "ordering": ["-created_at"],
            },
        ),
    ]
