# Generated by Django 4.2.13 on 2026-06-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0002_user_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refreshtoken",
            name="token",
            field=models.TextField(unique=True),
        ),
    ]
