# Generated by Django 4.2.13 on 2026-06-17 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0003_alter_refreshtoken_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="OneTimeToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Valeur du token — UUID aléatoire unique",
                        unique=True,
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        choices=[
                            ("VERIFY_EMAIL", "Vérification email"),
                            ("RESET_PASSWORD", "Réinitialisation mot de passe"),
                            ("INVITATION", "Invitation employé"),
                        ],
                        help_text="Type de flux auquel ce token correspond",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Date/heure d'expiration du token"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date/heure d'utilisation — null si non encore utilisé",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Utilisateur auquel ce token est lié",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="one_time_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token usage unique",
                "verbose_name_plural": "Tokens usage unique",
                "db_table": "one_time_tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="one_time_to_token_48c3ae_idx"),
                    models.Index(
                        fields=["user", "token_type"],
                        name="one_time_to_user_id_7b0ff9_idx",
                    ),
                ],
            },
        ),
    ]
