# Generated by Django 4.2.13 on 2026-07-05 03:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountingDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Facture"),
                            ("purchase_order", "Bon de commande"),
                            ("receipt", "Reçu"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("fiscal_year", models.CharField(blank=True, max_length=4)),
                ("notes", models.TextField(blank=True)),
                ("file_path", models.CharField(max_length=500)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("preview_path", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_ocr", "En attente OCR"),
                            ("preprocessing", "Prétraitement"),
                            ("extracting", "Extraction"),
                            ("analyzing", "Analyse"),
                            ("extracted", "Extrait"),
                            ("validated", "Validé"),
                            ("pending_chain", "Ancrage en cours"),
                            ("certified", "Certifié"),
                            ("tampered", "Falsifié"),
                            ("failed", "Échec"),
                        ],
                        db_index=True,
                        default="pending_ocr",
                        max_length=20,
                    ),
                ),
                ("progress", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                (
                    "ocr_engine",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tesseract5", "Tesseract 5"),
                            ("easyocr", "EasyOCR"),
                            ("paddleocr", "PaddleOCR"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence", models.IntegerField(blank=True, null=True)),
                ("raw_text", models.TextField(blank=True)),
                ("ocr_fields", models.JSONField(blank=True, default=dict)),
                (
                    "document_number",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "supplier",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("invoice_date", models.DateField(blank=True, null=True)),
                (
                    "amount_ht",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "tva_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "amount_ttc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("XAF", "Franc CFA (BEAC)"),
                            ("EUR", "Euro"),
                            ("USD", "Dollar américain"),
                        ],
                        default="XAF",
                        max_length=3,
                    ),
                ),
                ("corrections", models.JSONField(blank=True, default=list)),
                ("validated_by", models.UUIDField(blank=True, null=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "hash_sha256",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("tx_hash", models.CharField(blank=True, max_length=100)),
                ("block_number", models.BigIntegerField(blank=True, null=True)),
                (
                    "blockchain",
                    models.CharField(blank=True, default="ethereum", max_length=20),
                ),
                ("anchored_at", models.DateTimeField(blank=True, null=True)),
                ("certified_pdf_path", models.CharField(blank=True, max_length=500)),
                ("certified_by", models.UUIDField(blank=True, null=True)),
                (
                    "journal_entry_id",
                    models.IntegerField(
                        blank=True,
                        help_text="id de l'Ecriture créée côté module Compta (pas de FK cross-service)",
                        null=True,
                    ),
                ),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "accounting_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("ocr_extracted", "Extraction OCR"),
                            ("ocr_validated", "Validation des données OCR"),
                            ("ocr_correction", "Correction OCR"),
                            ("certified", "Certification blockchain"),
                            ("integrity_check", "Vérification d'intégrité"),
                            ("integrity_alert", "Alerte d'intégrité"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("detail", models.TextField(blank=True)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[("system", "Système"), ("user", "Utilisateur")],
                        default="system",
                        max_length=10,
                    ),
                ),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_entries",
                        to="gestiondoc.accountingdocument",
                    ),
                ),
            ],
            options={
                "db_table": "document_audit_log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="accountingdocument",
            index=models.Index(
                fields=["tenant_id", "status"], name="doc_tenant_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountingdocument",
            index=models.Index(
                fields=["tenant_id", "created_at"], name="doc_tenant_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentauditlog",
            index=models.Index(
                fields=["tenant_id", "action"], name="audit_tenant_action_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentauditlog",
            index=models.Index(
                fields=["tenant_id", "timestamp"], name="audit_tenant_time_idx"
            ),
        ),
    ]
