# Generated by Django 4.2.13 on 2026-07-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentauditlog',
            name='action',
            field=models.CharField(choices=[('upload', 'Upload'), ('ocr_extracted', 'Extraction OCR'), ('ocr_validated', 'Validation des données OCR'), ('ocr_correction', 'Correction OCR'), ('certified', 'Certification blockchain'), ('journal_linked', 'Écriture comptable liée'), ('integrity_check', "Vérification d'intégrité"), ('integrity_alert', "Alerte d'intégrité")], db_index=True, max_length=30),
        ),
    ]
