"""
Plan comptable SYSCOHADA (OHADA révisé 2017).
Utilisé pour initialiser automatiquement les comptes d'un tenant.
"""

# Format : (numero, libelle, classe, type_compte)
# type_compte : ACTIF | PASSIF | CHARGE | PRODUIT
PLAN_COMPTABLE_SYSCOHADA = [
    # ── CLASSE 1 : RESSOURCES DURABLES ─────────────────────────
    ("101",  "Capital social",                                   1, "PASSIF"),
    ("104",  "Primes liées au capital social",                   1, "PASSIF"),
    ("111",  "Réserve légale",                                   1, "PASSIF"),
    ("118",  "Autres réserves",                                  1, "PASSIF"),
    ("120",  "Report à nouveau (solde créditeur)",               1, "PASSIF"),
    ("129",  "Report à nouveau (solde débiteur)",                1, "ACTIF"),
    ("130",  "Résultat net de l'exercice (bénéfice)",            1, "PASSIF"),
    ("139",  "Résultat net de l'exercice (perte)",               1, "ACTIF"),
    ("161",  "Emprunts ordinaires",                              1, "PASSIF"),
    ("162",  "Crédit de trésorerie",                             1, "PASSIF"),
    ("163",  "Avances reçues de l'État",                         1, "PASSIF"),
    ("164",  "Dettes de location-financement",                   1, "PASSIF"),
    ("171",  "Dettes rattachées à des participations",           1, "PASSIF"),
    ("181",  "Dettes envers les associés",                       1, "PASSIF"),
    ("191",  "Provisions financières pour risques",              1, "PASSIF"),
    ("194",  "Provisions pour charges à répartir",               1, "PASSIF"),
    # ── CLASSE 2 : IMMOBILISATIONS ───────────────────────────────
    ("211",  "Terrains",                                         2, "ACTIF"),
    ("212",  "Agencements et aménagements de terrains",          2, "ACTIF"),
    ("221",  "Bâtiments sur sol propre",                         2, "ACTIF"),
    ("222",  "Bâtiments sur sol d'autrui",                       2, "ACTIF"),
    ("224",  "Matériel et outillage industriel et commercial",   2, "ACTIF"),
    ("228",  "Autres bâtiments",                                 2, "ACTIF"),
    ("231",  "Matériel",                                         2, "ACTIF"),
    ("232",  "Matériel informatique",                            2, "ACTIF"),
    ("233",  "Mobilier de bureau",                               2, "ACTIF"),
    ("241",  "Matériel de transport",                            2, "ACTIF"),
    ("244",  "Matériel de bureau",                               2, "ACTIF"),
    ("251",  "Avances et acomptes versés sur immobilisations",   2, "ACTIF"),
    ("261",  "Titres de participation",                          2, "ACTIF"),
    ("271",  "Autres immobilisations financières",               2, "ACTIF"),
    ("281",  "Amortissements — Bâtiments",                       2, "ACTIF"),
    ("283",  "Amortissements — Matériel",                        2, "ACTIF"),
    ("284",  "Amortissements — Matériel de transport",           2, "ACTIF"),
    ("285",  "Amortissements — Matériel informatique",           2, "ACTIF"),
    # ── CLASSE 3 : STOCKS ────────────────────────────────────────
    ("301",  "Marchandises",                                     3, "ACTIF"),
    ("302",  "Emballages commerciaux",                           3, "ACTIF"),
    ("321",  "Matières premières et fournitures liées",          3, "ACTIF"),
    ("322",  "Matières et fournitures consommables",             3, "ACTIF"),
    ("331",  "Encours de production de biens",                   3, "ACTIF"),
    ("341",  "Produits semi-ouvrés",                             3, "ACTIF"),
    ("351",  "Produits finis",                                   3, "ACTIF"),
    ("391",  "Dépréciation des stocks — Marchandises",           3, "ACTIF"),
    ("394",  "Dépréciation des stocks — Matières premières",     3, "ACTIF"),
    # ── CLASSE 4 : TIERS ──────────────────────────────────────────
    ("401",  "Fournisseurs",                                     4, "PASSIF"),
    ("402",  "Fournisseurs — Effets à payer",                    4, "PASSIF"),
    ("408",  "Fournisseurs — Factures non parvenues",            4, "PASSIF"),
    ("409",  "Fournisseurs — Avances et acomptes versés",        4, "ACTIF"),
    ("411",  "Clients",                                          4, "ACTIF"),
    ("412",  "Clients — Effets à recevoir",                      4, "ACTIF"),
    ("418",  "Clients — Produits non encore facturés",           4, "ACTIF"),
    ("419",  "Clients — Avances et acomptes reçus",              4, "PASSIF"),
    ("421",  "Personnel — Rémunérations dues",                   4, "PASSIF"),
    ("422",  "Personnel — Acomptes versés",                      4, "ACTIF"),
    ("423",  "Personnel — Oppositions, saisies-arrêts",          4, "PASSIF"),
    ("424",  "Personnel — Œuvres sociales internes",             4, "PASSIF"),
    ("425",  "Personnel — Charges à payer",                      4, "PASSIF"),
    ("431",  "Organismes sociaux — CNPS cotisations",            4, "PASSIF"),
    ("432",  "Organismes sociaux — Autres",                      4, "PASSIF"),
    ("441",  "État — Impôts et taxes",                           4, "PASSIF"),
    ("442",  "État — Impôts sur le revenu des personnes",        4, "PASSIF"),
    ("443",  "État — Taxes sur le chiffre d'affaires",           4, "PASSIF"),
    ("4431", "État — TVA facturée (collectée)",                  4, "PASSIF"),
    ("4432", "État — TVA due (sur encaissements)",               4, "PASSIF"),
    ("4451", "État — TVA sur immobilisations",                   4, "ACTIF"),
    ("4452", "État — TVA déductible sur achats",                 4, "ACTIF"),
    ("4454", "État — TVA sur prestations de services",           4, "ACTIF"),
    ("4455", "État — TVA à décaisser",                           4, "PASSIF"),
    ("447",  "État — IRPP à reverser",                           4, "PASSIF"),
    ("449",  "État — Crédit de TVA",                             4, "ACTIF"),
    ("451",  "Associés — Comptes courants",                      4, "PASSIF"),
    ("461",  "Débiteurs divers",                                 4, "ACTIF"),
    ("462",  "Créditeurs divers",                                4, "PASSIF"),
    ("471",  "Comptes d'attente débiteurs",                      4, "ACTIF"),
    ("472",  "Comptes d'attente créditeurs",                     4, "PASSIF"),
    ("476",  "Charges constatées d'avance",                      4, "ACTIF"),
    ("477",  "Produits constatés d'avance",                      4, "PASSIF"),
    ("481",  "Dettes sur acquisitions d'immobilisations",        4, "PASSIF"),
    ("491",  "Dépréciation des comptes clients",                 4, "ACTIF"),
    # ── CLASSE 5 : TRÉSORERIE ────────────────────────────────────
    ("511",  "Valeurs à l'encaissement",                         5, "ACTIF"),
    ("514",  "Chèques à encaisser",                              5, "ACTIF"),
    ("521",  "Banques locales — dépôts ordinaires",              5, "ACTIF"),
    ("522",  "Banques locales — dépôts à terme",                 5, "ACTIF"),
    ("524",  "Banques étrangères",                               5, "ACTIF"),
    ("531",  "Chèques postaux (CCP)",                            5, "ACTIF"),
    ("532",  "Mobile Money",                                     5, "ACTIF"),
    ("551",  "Crédits de trésorerie — Banques",                  5, "PASSIF"),
    ("571",  "Caisse principale",                                5, "ACTIF"),
    ("572",  "Caisse secondaire",                                5, "ACTIF"),
    ("581",  "Virements de fonds",                               5, "ACTIF"),
    # ── CLASSE 6 : CHARGES ───────────────────────────────────────
    ("601",  "Achats de marchandises",                           6, "CHARGE"),
    ("602",  "Achats de matières premières et fournitures",      6, "CHARGE"),
    ("604",  "Achats de matières et fournitures consommables",   6, "CHARGE"),
    ("605",  "Autres achats",                                    6, "CHARGE"),
    ("606",  "Achats non stockés — matières et fournitures",     6, "CHARGE"),
    ("608",  "Achats — frais accessoires",                       6, "CHARGE"),
    ("611",  "Transports sur achats",                            6, "CHARGE"),
    ("612",  "Transports sur ventes",                            6, "CHARGE"),
    ("613",  "Transports pour le compte de tiers",               6, "CHARGE"),
    ("614",  "Transports du personnel",                          6, "CHARGE"),
    ("621",  "Sous-traitance générale",                          6, "CHARGE"),
    ("622",  "Locations et charges locatives",                   6, "CHARGE"),
    ("623",  "Redevances de crédit-bail",                        6, "CHARGE"),
    ("624",  "Entretiens, réparations et maintenance",           6, "CHARGE"),
    ("625",  "Primes d'assurances",                              6, "CHARGE"),
    ("626",  "Études, recherches et documentation",              6, "CHARGE"),
    ("627",  "Publicité, publications, relations publiques",     6, "CHARGE"),
    ("628",  "Frais de télécommunications",                      6, "CHARGE"),
    ("629",  "Frais de déplacements, missions et réceptions",    6, "CHARGE"),
    ("631",  "Frais bancaires",                                  6, "CHARGE"),
    ("632",  "Charges fiscales et parafiscales",                 6, "CHARGE"),
    ("633",  "Autres impôts et taxes",                           6, "CHARGE"),
    ("641",  "Appointements et salaires bruts",                  6, "CHARGE"),
    ("642",  "Commissions et courtages",                         6, "CHARGE"),
    ("643",  "Indemnités et avantages divers",                   6, "CHARGE"),
    ("644",  "Charges sociales — CNPS",                          6, "CHARGE"),
    ("645",  "IRPP sur salaires",                                6, "CHARGE"),
    ("646",  "Cotisations diverses",                             6, "CHARGE"),
    ("651",  "Pertes sur créances irrécouvrables",               6, "CHARGE"),
    ("652",  "Charges pour dépréciations et provisions",         6, "CHARGE"),
    ("661",  "Charges d'intérêts",                               6, "CHARGE"),
    ("664",  "Pertes sur cessions de titres",                    6, "CHARGE"),
    ("671",  "Pertes sur créances liées à des participations",   6, "CHARGE"),
    ("672",  "Charges nettes sur cessions de VMP",               6, "CHARGE"),
    ("681",  "Dotations aux amortissements — immobilisations",   6, "CHARGE"),
    ("691",  "Dotations aux provisions — actif circulant",       6, "CHARGE"),
    ("694",  "Dotations aux provisions — risques à CT",          6, "CHARGE"),
    # ── CLASSE 7 : PRODUITS ──────────────────────────────────────
    ("701",  "Ventes de marchandises",                           7, "PRODUIT"),
    ("702",  "Ventes de produits finis",                         7, "PRODUIT"),
    ("703",  "Ventes de produits intermédiaires",                7, "PRODUIT"),
    ("704",  "Ventes de produits résiduels",                     7, "PRODUIT"),
    ("705",  "Travaux facturés",                                 7, "PRODUIT"),
    ("706",  "Services vendus",                                  7, "PRODUIT"),
    ("707",  "Produits accessoires",                             7, "PRODUIT"),
    ("708",  "Produits des activités annexes",                   7, "PRODUIT"),
    ("721",  "Production immobilisée — immobilisations corp.",   7, "PRODUIT"),
    ("722",  "Production immobilisée — immobilisations incorp.", 7, "PRODUIT"),
    ("741",  "Subventions d'exploitation",                       7, "PRODUIT"),
    ("742",  "Subventions d'équilibre",                          7, "PRODUIT"),
    ("751",  "Produits des cessions courantes d'immobilisations",7, "PRODUIT"),
    ("761",  "Revenus des participations",                       7, "PRODUIT"),
    ("762",  "Revenus des autres immobilisations financières",   7, "PRODUIT"),
    ("764",  "Revenus des valeurs mobilières de placement",      7, "PRODUIT"),
    ("766",  "Gains de change",                                  7, "PRODUIT"),
    ("771",  "Subventions d'investissement virées au résultat",  7, "PRODUIT"),
    ("781",  "Reprises de provisions — charges d'exploitation",  7, "PRODUIT"),
    ("791",  "Reprises de provisions — actif circulant",         7, "PRODUIT"),
    # ── CLASSE 8 : HAO (Hors Activités Ordinaires) ────────────────
    ("811",  "Valeurs comptables des cessions d'immob.",         8, "CHARGE"),
    ("812",  "Valeurs comptables des cessions VMP",              8, "CHARGE"),
    ("821",  "Produits des cessions d'immobilisations",          8, "PRODUIT"),
    ("822",  "Produits des cessions de VMP",                     8, "PRODUIT"),
    ("831",  "Charges HAO diverses",                             8, "CHARGE"),
    ("841",  "Produits HAO divers",                              8, "PRODUIT"),
    ("851",  "Dotations HAO aux amortissements",                 8, "CHARGE"),
    ("861",  "Reprises HAO de provisions",                       8, "PRODUIT"),
    ("871",  "Impôts sur les bénéfices",                         8, "CHARGE"),
    ("888",  "Subventions d'investissement",                     8, "PRODUIT"),
]

JOURNAUX_STANDARDS = [
    ("VTE",   "Journal des ventes",          "VENTES"),
    ("ACH",   "Journal des achats",          "ACHATS"),
    ("BNQ",   "Journal de banque",           "BANQUE"),
    ("CAI",   "Journal de caisse",           "CAISSE"),
    ("OD",    "Opérations diverses",         "OD"),
]
