# Generated by Django 4.2.13 on 2026-06-18 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FactureFournisseur",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("numero_interne", models.CharField(blank=True, max_length=30)),
                (
                    "numero_fournisseur",
                    models.CharField(
                        blank=True,
                        help_text="Numéro sur la facture du fournisseur",
                        max_length=100,
                    ),
                ),
                ("fournisseur_nom", models.CharField(max_length=200)),
                ("fournisseur_email", models.EmailField(blank=True, max_length=254)),
                (
                    "devise",
                    models.CharField(
                        choices=[
                            ("XAF", "Franc CFA (BEAC)"),
                            ("EUR", "Euro"),
                            ("USD", "Dollar américain"),
                        ],
                        default="XAF",
                        max_length=3,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("RECUE", "Reçue"),
                            ("VALIDEE", "Validée"),
                            ("PAYEE", "Payée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="BROUILLON",
                        max_length=10,
                    ),
                ),
                ("date_reception", models.DateField(blank=True, null=True)),
                (
                    "date_facture",
                    models.DateField(help_text="Date sur la facture fournisseur"),
                ),
                ("date_echeance", models.DateField()),
                (
                    "tva_taux",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "factures_fournisseurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LigneFactureFournisseur",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
                (
                    "quantite",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                "db_table": "lignes_factures_fournisseurs",
            },
        ),
        migrations.RemoveConstraint(
            model_name="compte",
            name="unique_compte_tenant_numero",
        ),
        migrations.RemoveConstraint(
            model_name="exercice",
            name="unique_exercice_tenant_annee",
        ),
        migrations.RemoveConstraint(
            model_name="journal",
            name="unique_journal_tenant_code",
        ),
        migrations.AddField(
            model_name="ecriture",
            name="created_by",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="compte",
            unique_together={("tenant_id", "numero")},
        ),
        migrations.AlterUniqueTogether(
            name="exercice",
            unique_together={("tenant_id", "annee")},
        ),
        migrations.AlterUniqueTogether(
            name="journal",
            unique_together={("tenant_id", "code")},
        ),
        migrations.AddField(
            model_name="lignefacturefournisseur",
            name="compte_charge",
            field=models.ForeignKey(
                blank=True,
                help_text="Compte de charge OHADA (classe 6) à imputer",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lignes_achat",
                to="comptabilite.compte",
            ),
        ),
        migrations.AddField(
            model_name="lignefacturefournisseur",
            name="facture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes",
                to="comptabilite.facturefournisseur",
            ),
        ),
        migrations.AddField(
            model_name="facturefournisseur",
            name="ecriture",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facture_fournisseur",
                to="comptabilite.ecriture",
            ),
        ),
    ]
