# Generated by Django 4.2.13 on 2026-06-18 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comptabilite", "0002_ecriture_created_by_facture_fournisseur"),
    ]

    operations = [
        migrations.AddField(
            model_name="compte",
            name="is_actif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="compte",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Compte parent pour la hiérarchie SYSCOHADA",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sous_comptes",
                to="comptabilite.compte",
            ),
        ),
        migrations.AddField(
            model_name="compte",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="ecriture",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="exercice",
            name="date_cloture",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercice",
            name="resultat_net",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Résultat calculé à la clôture (produits - charges)",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="exercice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="facture",
            name="created_by",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facture",
            name="facture_origine",
            field=models.ForeignKey(
                blank=True,
                help_text="Facture d'origine pour un avoir",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avoirs",
                to="comptabilite.facture",
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="type_document",
            field=models.CharField(
                choices=[("FACTURE", "Facture"), ("AVOIR", "Avoir / Note de crédit")],
                default="FACTURE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="facturefournisseur",
            name="facture_origine",
            field=models.ForeignKey(
                blank=True,
                help_text="Facture d'origine pour un avoir fournisseur",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avoirs",
                to="comptabilite.facturefournisseur",
            ),
        ),
        migrations.AddField(
            model_name="facturefournisseur",
            name="type_document",
            field=models.CharField(
                choices=[
                    ("FACTURE", "Facture fournisseur"),
                    ("AVOIR", "Avoir fournisseur"),
                ],
                default="FACTURE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="facturefournisseur",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="journal",
            name="compte_contrepartie",
            field=models.ForeignKey(
                blank=True,
                help_text="Compte de contrepartie par défaut (ex: 521 pour BNQ)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journaux_contrepartie",
                to="comptabilite.compte",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="ligneecriture",
            name="lettre",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Code de lettrage (rapprochement facture/paiement)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="statut",
            field=models.CharField(
                choices=[
                    ("BROUILLON", "Brouillon"),
                    ("EMISE", "Émise"),
                    ("PARTIELLEMENT_PAYEE", "Partiellement payée"),
                    ("PAYEE", "Payée"),
                    ("ANNULEE", "Annulée"),
                ],
                default="BROUILLON",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="facturefournisseur",
            name="statut",
            field=models.CharField(
                choices=[
                    ("BROUILLON", "Brouillon"),
                    ("RECUE", "Reçue"),
                    ("VALIDEE", "Validée (en attente de paiement)"),
                    ("PARTIELLEMENT_PAYEE", "Partiellement payée"),
                    ("PAYEE", "Payée"),
                    ("ANNULEE", "Annulée"),
                ],
                default="BROUILLON",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PaiementFournisseur",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "devise",
                    models.CharField(
                        choices=[
                            ("XAF", "Franc CFA (BEAC)"),
                            ("EUR", "Euro"),
                            ("USD", "Dollar américain"),
                        ],
                        default="XAF",
                        max_length=3,
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("VIREMENT", "Virement bancaire"),
                            ("CHEQUE", "Chèque"),
                            ("ESPECES", "Espèces"),
                            ("MOBILE_MONEY", "Mobile Money"),
                        ],
                        max_length=15,
                    ),
                ),
                ("date_paiement", models.DateField()),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("created_by", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ecriture",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiement_fournisseur",
                        to="comptabilite.ecriture",
                    ),
                ),
                (
                    "facture_fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paiements_fournisseur",
                        to="comptabilite.facturefournisseur",
                    ),
                ),
            ],
            options={
                "db_table": "paiements_fournisseurs",
                "ordering": ["-date_paiement"],
            },
        ),
    ]
